[package]
name = "kernel"
version = "0.1.0"
authors = ["Yuze Fu <i@xfox.me>"]
edition = "2018"

[dependencies]
rlibc = "1.0.0"
boot = { path = "../boot" }
embedded-graphics = "0.6.2"
log = "0.4"
xmas-elf = "0.7"
x86_64 = "0.11.0"
spin = "0.5.2"
